### ISSUE TITLE
[BUG] VS performance warning at startup

### ISSUE THREAD

**Issue by MagicAndre1981** [luminous-software/start-page-plus-64-bit#12]
**Describe the bug**

when I start VS 2022 I now get a warning, that Start Page+ slows down Visual Studio startup

**Expected behavior**

no warning

**Screenshots**

![image](https://user-images.githubusercontent.com/8274816/234192418-a09c8eea-9a7e-4efb-bc48-b5005d255b24.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11 22621.x
 - Version [e.g. 22] VS 2022 17.4 LTSC

**Comment by yannduran** [comment]
I've seen this occasionally when I'm debugging in the experimental instance, where it just takes longer to get everything ready, or if the code execution has stopped at a break point. 

But I don't recall seeing it when the version I've installed in my VS was compiled as _**release**_. Maybe I've seen it if the version I've installed to test was compiled as **_debug_**, but I don't recall that happening.

How often do you see that message? 135 seconds is a LOT!

I just checked inside the v0.19 vsix container & it has pdb files, so it's a **_debug_** version. I'll make sure that v0.20 is a **_release_** version.

**Comment by MagicAndre1981** [comment]
I was also suprised when I saw the message, there was no 135s delay, start was normal.

**Comment by yannduran** [comment]
It wouldn't the first time that VS has been known to lie ;-)

**Comment by MagicAndre1981** [comment]
> I just checked inside the v0.19 vsix container & it has pdb files, so it's a **_debug_** version. I'll make sure that v0.20 is a **_release_** version.

Maybe this is the cause of #10? So debug includes the dlls and release not?

**Comment by yannduran** [comment]
No, both **_debug_** & **_release_** versions normally contain all the required dlls in the vsix. The **_debug_** version also contains the debug files (*.pdb).

Btw, the dlls that you see in the **_bin/debug_** & **_bin/release_** folders don't really mean anything. It's only what's in the vsix that matters, because that's all you'll ever need to install the extension.

In fact there are a couple of Nuget packages that have `ExcludedAssets=runtime` manually added in the project file. Mads has advised us that without this, it just makes the bin folders messy, and makes the overall vsix file size much bigger. The `Community.VisualStudio.Toolkit` Nuget package is a good example of this. Without `ExcludedAssets=runtime`, you get dlls for the entire VS SDK, on which the toolkit is based. The `Community.VisualStudio.Toolkit` dll file already has those classes compiled into it, so there's no need for the runtime files to be included in the vsix separately.

Normally that applies to any dependencies that an assembly requires. For some reason, even explicitly adding packages for the "missing" dlls to satisfy the errors we're seeing isn't including those dlls in the vsix, and I can't for the life of me figure out why.

So when I add the `Microsoft.Extensions.DependencyInjection` package, there's no need to also add any of its dependencies (such as `Microsoft.Extensions.DependencyInjection.Abstractions`. I hope I've explained that well enough.

**Comment by yannduran** [comment]
Are you still having this problem with v0.16.20?

**Comment by MagicAndre1981** [comment]
The entry is gone 

![image](https://user-images.githubusercontent.com/8274816/235060638-b937b5e2-df71-4e68-bffb-01ec3abb58eb.png)

Looks like this was really a debug/release build issue. I'll close it for now and reopen it if it occurs later again.
