### ISSUE TITLE
[FEATURE] Hide StartPage+ on solution load, show on solution close

### ISSUE THREAD

**Issue by MagicAndre1981** [luminous-software/start-page-plus-64-bit#5]
**Is your feature request related to a problem? Please describe.**

On a solution load, StartPage+ stays open

**Describe the solution you'd like**

Add an option to hide StartPage+ on solution load and restore te StartPage on solution close

**Describe alternatives you've considered**

Currently you have to close and reopen StartPage+ on your own.

Originally[ reported on VS2019 version](https://github.com/luminous-software/start-page-plus/issues/63), but still relevant.

**Comment by yannduran** [comment]
I don't use Start Page+ that way myself, so it hadn't occurred to me that anyone would want to close it after a solution had loaded. I pin the tab, so I have an easy way to get to it instead of `View` | `Start Page+`.

I don't see why it can't be an option though, **_IF_** I can handle the solution loaded event properly. Same as your feature request in  [issue luminous-software/start-page-plus-64-bit#13](https://github.com/luminous-software/start-page-plus-64-bit/issues/13). I've got an idea that I'll try out for them.

**Comment by yannduran** [comment]
Implemented in v0.21

**Comment by MagicAndre1981** [comment]
> Implemented in v0.21

works fine 🥳🙌
